version: "3.8"
services:
  web:
    build: ./app
    image: 097984306046.dkr.ecr.us-east-2.amazonaws.com/workshop2_web
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=nc_tutorials_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=18.219.140.74
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=18.219.140.74
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 097984306046.dkr.ecr.us-east-2.amazonaws.com/workshop2_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: